### PR TITLE
Group 1 - Solution for Language Detector 

### PR DESCRIPTION
**Pull request by alothings**
Group 1 Team members
- Demetrios Koziris
- Alonso Gutierrez
- Andrew Lor

### CODE REVIEW

**Comment by taqpol** [comment]
```
def add(*args):
    return reduce(lambda x,y: x+y, args)
```

Why not just do sum(args)?

```
def repeat_last_operation(calc):
    if len(calc['history']) > 0:
        record = calc['history'][-1]
        return perform_operation(calc, record[1], record[2])
```

I don't think it's necessary to explicitly call the `perform_operation` function; calling the last item in the operation history automatically invokes that function. At least, that's how I think it works, since that's what we did.

**Comment by demetrios-koziris** [comment]
Using reduce was more fun than just doing sum()      :)
Also I think you're right about the history. We should just be returning the result of the last operation rather than re-invoking it.

**Comment by taqpol** [comment]
Actually, calling reduce on an empty sequence throws a TypeError. Sum simply returns 0 in that case, so sum is definitely the safer option. Besides, it's a built-in, so it's practically begging for you to use it.

**Comment by demetrios-koziris** [comment]
Good catch. We can handle that by giving reduce an initial value of 0:
`reduce(lambda x,y: x+y, [], 0)`
You're right about using built in stuff, but in this case, getting the extra practice of implementing it ourselves is nice :P

**Pull request closed without merging**
